---
--- Generated by Luanalysis
--- Created by binghong.shen_187191.
--- DateTime: 2022/5/26 14:00
---
function OnClientExecuteReq(context, param1, param2, param3)

	local this_target = ScriptLib.GetContextGadgetConfigId(context)
	--ScriptLib.PrintLog("##config="..this_target)
	local this_group = ScriptLib.GetContextGroupId(context)

	--if (param1 == 201) then
	--	ScriptLib.SetWorktopOptionsByGroupId(context, this_group, this_target, {437})
	--else
	--	ScriptLib.SetWorktopOptionsByGroupId(context, this_group, this_target, {})
	--end

end
