---
--- Generated by Luanalysis
--- Created by binghong.shen_187191.
--- DateTime: 2022/6/13 14:29
---
function OnClientExecuteReq(context, param1, param2, param3)

	local this_target = ScriptLib.GetContextGadgetConfigId(context)
	--ScriptLib.PrintLog("##config="..this_target)
	local this_group = ScriptLib.GetContextGroupId(context)

	if (param1 == 0) then
		ScriptLib.SetWorktopOptionsByGroupId(context, this_group, this_target, {})
	else
		ScriptLib.SetWorktopOptionsByGroupId(context, this_group, this_target, {param1})
	end
	return 0
end
